site_name: Redon Hub Docs
site_description: 'Documentation for https://github.com/Redon-Tech/Redon-Hub/'
site_author: 'Redon Tech'
docs_dir: docs/
repo_name: 'Redon-Tech/Redon-Hub'
repo_url: 'https://github.com/Redon-Tech/Redon-Hub/'
nav:
    - Home: index.md
    - Test: test.md

theme:
  features:
    - navigation.instant
    - navigation.tabs
  name: 'material'
  palette:
    - scheme: slate
      primary: indigo
      accent: red
      toggle:
        icon: material/brightness-3
        name: Dark
    - scheme: default
      primary: indigo
      accent: red
      toggle:
        icon: material/brightness-7
        name: Light

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.details
  - tables
  - def_list
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

extra_javascript:
  - swagger-ui-bundle.js