site_name: Redon Hub Docs
site_description: 'Documentation for https://github.com/Redon-Tech/Redon-Hub/'
site_author: 'Redon Tech'
docs_dir: docs/
repo_name: 'Redon-Tech/Redon-Hub'
repo_url: 'https://github.com/Redon-Tech/Redon-Hub/'
nav:
    - Home: index.md
    - Setup:
      - Initial Setup: setup/index.md
    - Advanced Usage:
      - Customization: advanced/customization.md
theme:
  features:
    - navigation.instant
    - navigation.tabs
  name: 'material'
  palette:
    scheme: slate
    primary: black
    accent: red
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - tables
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true